//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace journalProject.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Доступ
    {
        public int ID { get; set; }
        public Nullable<int> УчительID { get; set; }
        public Nullable<int> КлассID { get; set; }
        public Nullable<int> ПредметID { get; set; }
    
        public virtual Класс Класс { get; set; }
        public virtual Пользователь Пользователь { get; set; }
        public virtual Предмет Предмет { get; set; }
    }
}
