//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace journalProject.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Занятие_ученик
    {
        public int ID { get; set; }
        public int УченикID { get; set; }
        public int ЗанятиеID { get; set; }
        public Nullable<int> Оценка { get; set; }
        public string Присутствие { get; set; }
    
        public virtual Занятие Занятие { get; set; }
        public virtual Ученик Ученик { get; set; }
    }
}
