//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace journalProject.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Занятие
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Занятие()
        {
            this.Занятие_ученик = new HashSet<Занятие_ученик>();
        }
    
        public int ID { get; set; }
        public int КлассID { get; set; }
        public int ПредметID { get; set; }
        public Nullable<int> УчительID { get; set; }
        public System.DateTime Дата { get; set; }
        public int КабинетID { get; set; }
        public int ТемаID { get; set; }
    
        public virtual Кабинет Кабинет { get; set; }
        public virtual Предмет Предмет { get; set; }
        public virtual Тема Тема { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Занятие_ученик> Занятие_ученик { get; set; }
        public virtual Класс Класс { get; set; }
        public virtual Пользователь Пользователь { get; set; }
    }
}
