//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace journalProject.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Оценка_урок
    {
        public int ID { get; set; }
        public int Оценка { get; set; }
        public int ДневникID { get; set; }
        public int УрокID { get; set; }
    
        public virtual Дневник Дневник { get; set; }
        public virtual Урок Урок { get; set; }
    }
}
