//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace journalProject.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Урок
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Урок()
        {
            this.Оценка_урок = new HashSet<Оценка_урок>();
        }
    
        public int ID { get; set; }
        public int КлассID { get; set; }
        public int ПредметID { get; set; }
        public int УчительID { get; set; }
        public System.DateTime Дата { get; set; }
    
        public virtual Класс Класс { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Оценка_урок> Оценка_урок { get; set; }
        public virtual Пользователь Пользователь { get; set; }
        public virtual Предмет Предмет { get; set; }
    }
}
